import { BadRequestException, Injectable } from '@nestjs/common';
import { PaginationDto } from '../../common/dto/pagination.dto';
import { PrismaService } from '../../prisma/prisma.service';
import { CreateStockTransferDto } from './dto/stock-transfer.dto';
@Injectable()
export class StockTransfersService {
  constructor(private readonly prisma: PrismaService) {}
  async findAll(query:PaginationDto){const where=query.search?{OR:[{reference:{contains:query.search,mode:'insensitive' as const}},{fromLocation:{contains:query.search,mode:'insensitive' as const}},{toLocation:{contains:query.search,mode:'insensitive' as const}}]}:{};const [data,total]=await Promise.all([this.prisma.stockTransfer.findMany({where,include:{items:{include:{product:true}}},skip:(query.page-1)*query.limit,take:query.limit,orderBy:{transferDate:'desc'}}),this.prisma.stockTransfer.count({where})]);return{data,total,page:query.page,limit:query.limit}}
  async create(dto:CreateStockTransferDto,addedBy:string){if(dto.fromLocation.trim()===dto.toLocation.trim())throw new BadRequestException('Source and destination locations must be different');const products=await this.prisma.product.findMany({where:{id:{in:dto.items.map(i=>i.productId)}}});if(products.length!==new Set(dto.items.map(i=>i.productId)).size)throw new BadRequestException('One or more products were not found');for(const item of dto.items){const product=products.find(p=>p.id===item.productId)!;if(product.stockQty<item.quantity)throw new BadRequestException(`Insufficient stock for ${product.name}`)}const subtotal=dto.items.reduce((sum,item)=>{const p=products.find(x=>x.id===item.productId)!;return sum+item.quantity*Number(p.unitPrice)},0);const count=await this.prisma.stockTransfer.count();return this.prisma.stockTransfer.create({data:{reference:dto.reference?.trim()||`ST-${new Date().getFullYear()}-${String(count+1).padStart(5,'0')}`,transferDate:dto.transferDate?new Date(dto.transferDate):new Date(),fromLocation:dto.fromLocation,toLocation:dto.toLocation,status:dto.status,shippingCharges:dto.shippingCharges??0,notes:dto.notes,total:subtotal+(dto.shippingCharges??0),addedBy,items:{create:dto.items.map(item=>{const product=products.find(p=>p.id===item.productId)!;return{productId:item.productId,quantity:item.quantity,unitPrice:product.unitPrice,lineTotal:item.quantity*Number(product.unitPrice)}})}},include:{items:{include:{product:true}}}})}
}
